version: '3.3'

services:
  mysqlku:
    restart: always
    image: mysql:5.7
    volumes: 
      - /root/mysql:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: nano123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress 
  wordpressku:
    restart: always
    depends_on: 
     - mysqlku
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysqlku:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
  phpmyadminku:
    depends_on:
      - mysqlku
    restart: always
    environment:
     PMA_HOST: mysqlku
     MYSQL_ROOT_PASSWORD: nano123
    ports:
     - "8070:80"
    image: phpmyadmin/phpmyadmin
    
